name: Run Build

on:
  workflow_dispatch:
    inputs:
      appName:
        description: "Custom application name"
        required: false
        default: "Test App"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cli

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Ensure CLI scripts have executable perms
      - name: Make CLI scripts executable
        run: chmod +x build.sh upload.sh

      # Generate a date-based build version
      - name: Generate Version
        run: |
          VERSION=$(date +'%Y.%m.%d').${{ github.run_number }}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        
      # CLI call to simulated build process
      - name: Run Build
        run: |
          appName="${{ inputs.appName }}"
          ./build.sh --platform Android --project-name "$appName" --version "$VERSION"

      # CLI call to simulated upload process
      - name: Upload
        env:
          UPLOAD_TOKEN: dummy-token
        run: |
          for file in build/Android/*; do
            ./upload.sh android "$file"
          done